name: notea_frontend
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  quiver: ^3.2.1
  uuid: ^3.0.7
  http: ^0.13.6
  connectivity_plus: ^4.0.1
  progress_state_button: ^1.0.4

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  image_picker: ^1.0.0
  multi_select_flutter: ^4.1.3
  google_ml_kit: ^0.15.0
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
